# This is a basdic workflow to help you get started with Actions

name: Stop tomcat server
  jobs.build.steps[*].continue-on-error
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: delete directory
        run: rm -rf /opt/AR
      - name: Clone Repositry
        run: git clone https://github.com/Demnu/AutumnRoomsBookings.git /opt/AR
      - name: Download servlet-api.jar
        run: (cd /opt/AR/WEB-INF/classes/pkg ; wget http://www.java2s.com/Code/JarDownload/servlet/servlet-api.jar.zip)
      - name: Unzip servlet.zip
        run: (cd /opt/AR/WEB-INF/classes/pkg ; unzip servlet-api.jar.zip)
      - name: Compile classes
        run: (cd opt/WEB-INF/classes/pkg ; javac -cp servlet-api.jar *java)
        if: success()
      - name: Create War
        run: (cd /opt/AR ; jar -cvf AR.war *) 
        if: success()
      - name: Move War File to Webapps
        run: mv /opt/AR/AR.war /opt/tomcat/webapps/
        if: success()
      - name: Restart Tomcat server
        run: /opt/tomcat/bin/./catalina.sh stop
    


      

